# Generated by Django 4.2 on 2023-05-13 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='confirmed',
            new_name='confirm',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
