# Generated by Django 4.2 on 2023-05-01 12:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('objets', django.db.models.manager.Manager()),
            ],
        ),
    ]
