# Generated by Django 4.2 on 2023-05-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
            ],
        ),
    ]
